version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: infrawatch
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: infrawatch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "infrawatch"]
      interval: 5s
      retries: 5

  checker:
    build: .
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres

volumes:
  postgres_data: